name: Run script every minute

on:
  # schedule:
  # - cron: '* * * * *' # запуск кожну хвилину
  push:
    branches:
      - master
jobs:
  update_json_file:
    runs-on: ubuntu-latest
    env:
      TYPE: ${{secrets.TYPE}} 
      PROJECT_ID: ${{secrets.PROJECT_ID}}
      PRIVATE_KEY_ID: ${{secrets.PRIVATE_KEY_ID}}
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}} 
      CLIENT_EMAIL: ${{secrets.CLIENT_EMAIL}} 
      CLIENT_ID:  ${{secrets.CLIENT_ID}}
      AUTH_URI: ${{secrets.AUTH_URI}} 
      TOKEN_URI: ${{secrets.TOKEN_URI}} 
      AUTH_PROVIDER_X509_CERT_URL: ${{secrets.AUTH_PROVIDER_X509_CERT_URL}} 
      CLIENT_X509_CERT_URL:  ${{secrets.CLIENT_X509_CERT_URL}}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node getGoogleSheetData.js

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "accaunt01.13@gmail.com"
          git config --local user.name "Mariia Postovik"
          git add output.json
          git commit -m "Update data [skip ci]"
          git push
