name: Run script every minute

on:
  # schedule:
  #   - cron: '* * * * *' # запуск кожну хвилину
  push:
    branches:
      - master
jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.CREDENTIALS }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node getGoogleSheetData.js
