name: Run script every minute

on:
  schedule:
    - cron: '* * * * *' # запуск кожну хвилину

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up environment variables
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node getGoogleSheetData.js
